// Generated by CoffeeScript 1.9.3
(function() {
  var Items;

  Items = new Mongo.Collection("items");

  if (Meteor.isClient) {
    Template.body.helpers({
      items: function() {
        return Items.find({}, {
          sort: {
            createdAt: -1
          }
        });
      }
    });
    Template.body.events({
      "submit .new-item": function(event) {
        var text;
        event.preventDefault();
        text = event.target.text.value;
        Items.insert({
          text: text,
          createdAt: new Date()
        });
        return event.target.text.value = "";
      }
    });
  }

  if (Meteor.isServer) {
    Meteor.startup(function() {});
  }

}).call(this);
